.gitattributes
.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/_sbt_build.yml
.github/workflows/pr.yml
.scalafix.conf
.scalafmt.conf
build.sbt
project/Dependencies.scala
project/build.properties
project/site.sbt

This is a partial pull request focused on setting up the directory structure, build process and pipeline. Publishing to Maven central will be in a subsequent PR.

Tsdk 42 generate mnemonics and main wallet key (scala)

---

README.md

Update the README with usage instructions.
Just write it
Tried the deployment
* TSDK-220
[TSDK-220]: https://topl.atlassian.net/browse/TSDK-220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

disable maven release

---

brambl-sdk/src/test/scala/co/topl/brambl/generators/ModelGenerators.scala
build.sbt
project/Dependencies.scala

Publish Model Generators
- update protobuf-specs
- update quivr
- create generators for **Brambl**   and Quivr
- Next Step: same task on Quivr
- Next Step: remove Quivr generator on Brmbl, and use Quivr published
-1 question about if we do want to publish both projects
publishLocal
* TODO

publish generators

---

.scala-steward.conf
project/Dependencies.scala

Group scala-steward Pr
https://github.com/VirtusLab/scala-steward-repos/pull/171#event-8507113235
next   scala-steward job
*

scala-steward-config

---

brambl-sdk/src/test/scala/co/topl/brambl/generators/ModelGenerators.scala

- remove unused trait
preparepr

remove unused trait

---

brambl-sdk/src/main/scala/co/topl/brambl/wallet/WalletApi.scala
crypto/src/main/scala/co/topl/crypto/encryption/VaultStore.scala

- Align with what is needed for brambl-cli
- Updates to signatures
- Added load functions (mirrors save)
- Tests will be added in a subsequent ticket.
- Ran `checkPR` and ensured was successful
* Part of TSDK-437

TSDK-437 Load + Extract Main Key + Derive Child Key 

---

brambl-sdk/src/main/scala/co/topl/brambl/dataApi/DataApi.scala
brambl-sdk/src/main/scala/co/topl/brambl/wallet/WalletApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockDataApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/WalletApiSpec.scala

Add Delete Wallet functionality. Supports the Ribn use case "remove account". 
- Added function in DataApi
- Added function in WalletApi
- Added unit tests
- ((unrelated to the task)) I also changed the order of the functions in WalletApi. These changes had no implementation changes. It was purely for readability sake.
- Added unit tests for the delete capabilities
- Ran `checkPR` and ensured successful
* Closes TSDK-438

TSDK-438 Delete Wallet

---

brambl-sdk/src/main/scala/co/topl/brambl/codecs/AddressCodecs.scala
brambl-sdk/src/main/scala/co/topl/brambl/utils/Encoding.scala
brambl-sdk/src/test/scala/co/topl/brambl/utils/EncodingSpec.scala

The goal is to provide encoding functions for the address codecs.
We implemented the Base58, and Base58Check algorithm.
Unit tests were added.
* TSDK-467

TSDK-467 Add encoding functions

---

brambl-sdk/src/main/scala/co/topl/brambl/codecs/AddressCodecs.scala
brambl-sdk/src/main/scala/co/topl/brambl/constants/NetworkConstants.scala
brambl-sdk/src/main/scala/co/topl/brambl/utils/Encoding.scala
brambl-sdk/src/test/scala/co/topl/brambl/codecs/AddressCodecTestCases.scala
brambl-sdk/src/test/scala/co/topl/brambl/codecs/AddressCodecsSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/utils/EncodingSpec.scala

The goal of this PR is to implement AddressCodec
The implementation just transforms from lock address to a base58check encoded string and back again.
Unit tests were added.
* TSDK-467

TSDK-467 Encoding functions

---

brambl-sdk/src/main/scala/co/topl/brambl/dataApi/BifrostQueryAlgebra.scala
brambl-sdk/src/main/scala/co/topl/brambl/dataApi/BifrostQueryInterpreter.scala

In a previous PR, GenusQuery was added to the DataApi. The Bifrost Query should of been added as well
Added Bifrost Query to DataApi
- Ran `checkPR` and ensured successful
- Used the changes in brambl-cli
* N/a

DataApi Quick Fix

---

project/build.properties

update sbt version 1.9.1

---

project/Dependencies.scala

Release v2.0.0-alpha4
Update dependency to latest protobuf-spec.
Tests are passing.
* N/A

Update dependencies for the latest protobuf specs

---

brambl-sdk/src/test/scala/co/topl/brambl/generators/ModelGenerators.scala

- Implement missing generators for group and series

Tech debt: generators:groupId, seriesId

---

project/Dependencies.scala

Update to latest protobuf release in preparation for release.
Update to latest protobuf release,
N/A
* TSDK-581

TSDK-581 Update to latest protobuf release

---

brambl-sdk/src/main/scala/co/topl/brambl/common/ContainsImmutable.scala
brambl-sdk/src/test/scala/co/topl/brambl/validation/TransactionSyntaxInterpreterMintingCaseProposalUpdateSpec.scala

Immutable Instance for value: Update Proposal
- implement immutable Instance, create a test for validation, (which actually does does not contains validation )
preparePR
BN-1219

BN-1219 - Update proposal immutable instances

---

brambl-sdk/src/test/scala/co/topl/brambl/validation/TransactionSyntaxInterpreterMintingCaseCSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/validation/TransactionSyntaxInterpreterRuleBSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/validation/pumls/invalid_case_7.puml
brambl-sdk/src/test/scala/co/topl/brambl/validation/pumls/invalid_case_8.puml

Syntax Interpreter Minting Spec: invalid_cases_7_8

---

brambl-sdk/src/main/scala/co/topl/brambl/validation/TransactionSyntaxError.scala
brambl-sdk/src/main/scala/co/topl/brambl/validation/TransactionSyntaxInterpreter.scala
brambl-sdk/src/test/scala/co/topl/brambl/validation/TransactionSyntaxInterpreterMintingCaseProposalUpdateSpec.scala

- BN-1246-update-proposal-validation 
-  new validation rule for proposal updated, simple rules, all values should be positives
- unit test
BN-1246

BN-1246-update-proposal-validation

---

brambl-sdk/src/main/scala/co/topl/brambl/builders/TransactionBuilderApi.scala
brambl-sdk/src/main/scala/co/topl/brambl/builders/UserInputValidations.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterAssetTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterGroupTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterLvlsTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSeriesTransferSpec.scala

Ease of use
Modified user error message and added notes in some documentation
ensure all tests pass
* n/a

Ease of use improvements - error message and documentation

---

documentation/docs/reference/transactions/minting.mdx
documentation/docs/reference/transactions/transfer.mdx

I moved a page to a different directory and did not update links to reflect
Update the links
ensured `npm run build` succeeded locally
* Part of TSDK--604

TSDK-604 Fixing broken links

---

documentation/docs/reference/getting-started.md
documentation/docs/reference/getting-started.mdx
documentation/docs/reference/locks/locks.mdx
documentation/docs/reference/locks/share-lock-addr.mdx
documentation/docs/reference/rpc.mdx
documentation/docs/reference/transactions/transactions.mdx
documentation/docs/reference/wallets/create.mdx
documentation/docs/reference/wallets/import.mdx
documentation/docs/reference/wallets/wallets.mdx

Document how to initialize a wallet
- Added getting started
- Added create a new wallet
- added import an existing wallet (via mnemonic)
tested locally
* closes TSDK-613

TSDK-613 Initialize Wallet (and Getting Started)

---

crypto/src/main/scala/co/topl/crypto/signing/ExtendedEd25519.scala

Fix bug that made tests flaky. 
Verified that the bug was happening because the keys parts of the generated derived private keys need to be 32 bytes long. Sometimes, this was not the case because of the implementation of BigInt. After checking the [BIP-32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) standard, we needed to implement the sec_256 serialization for big integers.
The implementation guaranteed that all numbers are always 32 bytes in length and thus the bug cannot happen again.
A scala-cli script was developed to reproduce the bug:
```scala
// You can run this code using scala-cli. Save it in a file called `testBug.sc` and run it with `scala-cli testBug.sc`
//> using scala 2.13
//> using repository sonatype-s01:releases
//> using dep …
```

TSDK-632 Fix bug.

---

brambl-sdk/src/main/scala/co/topl/brambl/dataApi/WalletStateAlgebra.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockWalletStateApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/CredentiallerInterpreterSpec.scala
service-kit/src/main/scala/co/topl/brambl/servicekit/WalletStateApi.scala
service-kit/src/test/scala/co/topl/brambl/servicekit/WalletStateApiSpec.scala

The goal of this PR is to add support to list interactions to the brambl sdk/service-kit.
We implemented new function in the `WalletStateAlgebra`.
Two unit tests were added.
* TSDK-631

TSDK-631 List interactions support

---

brambl-sdk/src/main/scala/co/topl/brambl/common/ContainsImmutable.scala
project/Dependencies.scala

update latest prototobuf Specs
compile, test

update latest prototobuf Specs

---

brambl-sdk/src/main/scala/co/topl/brambl/dataApi/BifrostQueryAlgebra.scala
brambl-sdk/src/main/scala/co/topl/brambl/dataApi/BifrostQueryInterpreter.scala
documentation/docs/reference/broadcast.mdx
documentation/docs/reference/rpc.mdx

Adding broadcast bifrost query to BramblSc
- Added broadcast function to Bifrost Query
- Documented it in the portal
Used it in brambl-cli and ensured integration tests pass
* Closes TSDK-635

TSDK-635 Broadcast

---

CHANGELOG.md
documentation/docs/reference/wallets/usage.mdx
documentation/docs/reference/wallets/wallets.mdx

To document how to obtain Walley Keys
- Changed section "Initialize a Wallet" to "Wallet Keys"
- Added subsection "Usage" under "Wallet Keys" that document extracted main key and deriving child keys
- Added examples for each
No code changes but ensured all examples run successfully
* closes TSDK-644

TSDK-644 Document Wallet Key Usage

---

CHANGELOG.md
documentation/docs/tutorials/tutorials/mint-asset.md
documentation/docs/tutorials/tutorials/simple-transfer.md

To add a tutorial for minting a custom asset from scratch.
- Added tutorial
- Minor update to a previous tutorial where the example excluded updating wallet state
No code changes but ensured all examples ran successfully
* Closes TSDK-648

TSDK-648 Mint Custom Asset Tutorial

---

CHANGELOG.md
brambl-sdk/src/main/scala/co/topl/brambl/display/QuivrDisplayOps.scala
brambl-sdk/src/main/scala/co/topl/brambl/display/StructDisplayOps.scala
brambl-sdk/src/main/scala/co/topl/brambl/display/ValidationErrorDisplayOps.scala
brambl-sdk/src/main/scala/co/topl/brambl/display/package.scala
brambl-sdk/src/test/scala/co/topl/brambl/display/DisplaySpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/CredentiallerInterpreterSpec.scala

To add Pretty Print capabilities (allow users to Display) a validation errors (including propositions and proofs) using the SDK.
Added DisplayOps for validation errors (Authorization and Syntax) as well as Proofs&Propositions in the display package.
- Added a new test to verify each error displays as expected
* TSDK-663

TSDK-664 Proof, Propositions, Validation Error Pretty Print/Display

---

brambl-sdk/src/main/scala/co/topl/brambl/validation/TransactionCostCalculatorInterpreter.scala
brambl-sdk/src/main/scala/co/topl/brambl/validation/algebras/TransactionCostCalculator.scala

Calculation of transaction cost no longer requires effect
Calculation of transaction cost no longer requires effect
BN-1424

BN-1424 Calculation of transaction cost no longer requires effect

---

CHANGELOG.md

Updated changelog in preparation for release
* n/a

Prepare for release: Updated changelog
