Topl/BramblSc

.github/CONTRIBUTING.md
README.md
build.sbt

To fix typos. It should say "BramblSc" or "Brambl"
Replaced all occurrences of "Bramble" with "Brambl"
- Sanity checked that code still compiles
- Verified that the GitHub links work
* Done as part of TSDK-240

Replaced all occurrences of Bramble with Brambl

---

brambl-sdk/src/main/scala/co/topl/brambl/routines/digests/Blake2b256Digest.scala
brambl-sdk/src/main/scala/co/topl/brambl/validation/Blake2b256DigestInterpreter.scala
brambl-sdk/src/main/scala/co/topl/brambl/validation/TransactionAuthorizationError.scala
brambl-sdk/src/main/scala/co/topl/brambl/validation/TransactionAuthorizationInterpreter.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/CredentiallerInterpreterSpec.scala
project/Dependencies.scala

When Authorization validation fails, a single AuthorizationFailed error is returned. This overwrites the QuivrRuntimeErrors that led to the authorization failure (useful information is lost). 
If available, include the QuivrRuntimeErrors that occurred if Authorization Validation fails. Note that these may not be the finalized errors; determining the proper errors to return in different cases will be revisited in [TSDK-252](https://topl.atlassian.net/browse/TSDK-252).
During testing, a bug was found in Blake2b256 and its validator; it is fixed as part of this PR
- Updated the affected unit test
- Ensured all existing tests pass
* Closes TSDK-304
[TSDK-252]: https://topl.atlassian.net/browse/TSDK-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

TSDK-304: Enhance AuthorizationFailed Error to include QuivrRuntimeErrors

---

brambl-sdk/src/main/scala/co/topl/brambl/routines/signatures/Ed25519Signature.scala
brambl-sdk/src/main/scala/co/topl/brambl/validation/Ed25519SignatureInterpreter.scala
brambl-sdk/src/main/scala/co/topl/brambl/wallet/CredentiallerInterpreter.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/CredentiallerInterpreterSpec.scala

A test unit test was not consistent. When running the test via Intellij IDE, it was consistently passing. However, the test is run via SBT (including Github actions), the result was inconsistent (sometimes passing, sometimes failing). 
Debugging revealed that the issue is caused by Ed25519Signature.createKeyPair (Ed25519.instance.deriveKeyPairFromSeed) not being deterministic when run in SBT. Specifically, the Verification Key returned was not the one expected. It came up today in EOD check-in that Ed25519.instance was not thread-safe.
- Updated the unit test to be more verbose
- Replaced the usage of `Ed25519.instance` with `new Ed25519`
- Updated the flaky test to be more verbose
- Manually ran the test suite using **SBT** 15 times consecutively to ensure the test _consistently_ passes …

TSDK-328 Fix flaky unit test

---

brambl-sdk/src/test/scala/co/topl/brambl/generators/ModelGenerators.scala

Currently tests in BramblSc mock PB models using hardcoded data. scalacheck generators for generating mock PB models are currently being implemented in the Bifrost repo. 
Implement model generators
TBD, replace specs in this PR or other.
preparePr
https://topl.atlassian.net/browse/BN-857

brambl models generators

---

crypto/src/main/scala/co/topl/crypto/encryption/cipher/Aes.scala
crypto/src/main/scala/co/topl/crypto/encryption/cipher/cipher.scala
crypto/src/main/scala/co/topl/crypto/encryption/kdf/Scrypt.scala
crypto/src/main/scala/co/topl/crypto/encryption/kdf/kdf.scala
crypto/src/test/scala/co/topl/crypto/encryption/cipher/AesSpec.scala
crypto/src/test/scala/co/topl/crypto/encryption/kdf/SCryptSpec.scala

For Encrypting a Keyfile, we need to have an implementation of a Cipher and a KDF (see image below). We will use AES as the cipher, and SCrypt as the KDF for the initial implementation.
- Added `cipher` package with `Cipher` trait and `kdf` package with `Kdf` trait in a new `encryption` package. `Cipher` has `encrypt` and `decrypt` while `Kdf` has `deriveKey`. Since different implementations of ciphers and kdfs will have their own parameters, the `Param` trait in each is empty and will be extended by the specific implementations.
- Added `Aes` in the `encryption.cipher` package. 
- Added SCrypt in the `encryption.kdf` package. 
- The implementation details of both were informed by an older implementation of generating a KeyFile. See …

TSDK-356 Add AES and SCrypt

---

crypto/src/main/scala/co/topl/crypto/generation/EntropyToSeed.scala
crypto/src/main/scala/co/topl/crypto/signing/Ed25519.scala
crypto/src/main/scala/co/topl/crypto/signing/ExtendedEd25519.scala

- All instances of the "public" Ed25519 share the same internal implementation instance.  This may lead to thread-safety issues in parallel environments
- The SecretKey and PublicKey classes were missing hashCode implementations which may confuse implementations of HashSet or HashMap
- Remove the singleton instances of Ed25519 from the ExtendedEd25519 and Ed25519 companion objects.  Create new internal instances each time
- Add hashcodes to the public key and secret key classes
- preparePR
N/A

Remove Singleton Ed25519 Instances

---

crypto/src/main/scala/co/topl/crypto/signing/ExtendedEd25519.scala
crypto/src/test/scala/co/topl/crypto/signing/ExtendedEd25519Spec.scala

A big use case of ExtendedEd25519 is to derive child key pairs given a path.
Added an exposed function within ExtendedEd25519 to derive a key pair from a child derivation path. 
- Updated ExtendedEd25519 tests to cover this function (it applies the test to the test vectors)
- Ensured all existing tests pass
* Closes TSDK-355

TSDK-355 Child Derivation path

---

brambl-sdk/src/main/scala/co/topl/brambl/dataApi/DataApi.scala
brambl-sdk/src/main/scala/co/topl/brambl/wallet/WalletApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockDataApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/WalletApiSpec.scala
crypto/src/main/scala/co/topl/crypto/generation/mnemonic/Entropy.scala
crypto/src/test/scala/co/topl/crypto/generation/mnemonic/EntropySpec.scala

Update WalletApi.createNewWallet based on some recent feedback
- When returning the mnemonic, return IndexedSeq[String] instead of a single String
- Use `for` comprehension in `createNewWallet`
- Update return type such that both types of errors will return (previously if a DataApi error occurs, the caller will not know)
- Update return type such that the VaultStore is also returned as well (in addition to mnemonic)
- Ensured all existing tests will pass
- ran `checkPR`
* N/A

Wallet fix

---

brambl-sdk/src/main/scala/co/topl/brambl/wallet/WalletApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/WalletApiSpec.scala

There was a complication in the implementation of the generic `createAndSaveNewWallet`.
I created the function using some type parameters so that it supports Monad operations
The tests were fixed.
* No tickets

Try to improve the design

---

brambl-sdk/src/main/scala/co/topl/brambl/routines/digests/Blake2b256Digest.scala
brambl-sdk/src/main/scala/co/topl/brambl/validation/Blake2b256DigestInterpreter.scala
crypto/src/main/scala/co/topl/crypto/accumulators/merkle/MerkleTree.scala
crypto/src/main/scala/co/topl/crypto/hash/Blake2b.scala
crypto/src/test/scala/co/topl/crypto/utils/Generators.scala
project/Dependencies.scala

We no longer want to depend on Scodec
Removed any remaining usages of Scodec and replaced with appropriate data types. Removed Scodec from dependencies
- Any tests that depended on scodec were updated as well
- Ensured all existing tests pass 
- Ran `checkPR`, ensured it passed
* Part of TSDK-413 => Updates to Bifrost are still required

TSDK-413 Removed all remaining usages of Scodec

---

brambl-sdk/src/main/scala/co/topl/brambl/dataApi/DataApi.scala
brambl-sdk/src/main/scala/co/topl/brambl/wallet/WalletApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockDataApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockHelpers.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/WalletApiSpec.scala

Made changes to WalletApi and DataApi to support the use case of updating a wallet's password
- added `updateMainKeyVaultStore` to DataApi
- Changed WalletApi's private `buildMainKeyVaultStore` to be exposed in the Algebra. 
- Added 2 additional functions to WalletApi's algebra; `updateWallet` and `updateWalletPassword`. The latter is implemented in the trait. The former is implemented in `make` using the new `DataApi.updateMainKeyVaultStore`
- Updated MockDataApi for tests to reflect the change in DataApi. I also mocked a way to trigger a save failure in `saveMainKeyVaultStore`
- Updated MockHelpers to re-instantiate `new ExtendedEd25519` each time its used (to fix flaky tests)
- Added unit tests for all the new functions + added an `afterEach` cleanup function to reset the persisted …

TSDK-419 Update Wallet + Update Wallet's Password

---

brambl-sdk/src/main/scala/co/topl/brambl/common/ContainsEvidence.scala
brambl-sdk/src/main/scala/co/topl/brambl/common/ContainsImmutable.scala
brambl-sdk/src/main/scala/co/topl/brambl/common/ContainsSignable.scala
brambl-sdk/src/main/scala/co/topl/brambl/syntax/LockSyntax.scala
brambl-sdk/src/main/scala/co/topl/brambl/syntax/TransactionIdSyntax.scala
brambl-sdk/src/main/scala/co/topl/brambl/validation/Blake2b256DigestInterpreter.scala
brambl-sdk/src/main/scala/co/topl/brambl/validation/TransactionAuthorizationInterpreter.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockHelpers.scala
brambl-sdk/src/test/scala/co/topl/brambl/generators/ModelGenerators.scala
project/Dependencies.scala

- protobuf-specs has been [updated](https://github.com/Topl/protobuf-specs/pull/54) to remove Identifier and Address super-types
- Also updated to remove separation of 32/64-length types
- Update codecs and generators with new protobuf-specs types
- Implemented in Bifrost
- #BN-963

TransactionId, Remove 32/64 Types

---

brambl-sdk/src/main/scala/co/topl/brambl/wallet/WalletApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/WalletApiSpec.scala
crypto/src/main/scala/co/topl/crypto/generation/mnemonic/Entropy.scala

Add API endpoint to import a wallet from a mnemonic
- Added importWallet, recoverWallet, and importWalletAndSave
- importWallet returns a constructed VaultStore from the mnemonic. This mirrors createNewWallet
- recoverWallet is meant to handle recovering local wallet data from the main key in a VaultStore and optionally a snapshot object. This function needs to be fleshed out more and is added in this ticket/PR as a placeholder. Comments & TODOs were added
- importWalletAndSave imports the wallet as a VaultStore and then saves it to the dataApi (as well as recovers additional data). This mirrors createAndSaveNewWallet
- Added new tests
- ran `checkPR` and ensured they all pass
* Closes TSDK-393

TSDK-393 Import Wallet (not including recovery)

---

.github/release-drafter.yml
.github/workflows/maven_release.yml
.github/workflows/release_drafter.yml

Enable publishing TSDK tooling to Maven.
Enable the existing Maven release workflow, and add additional workflows following the [sbt-ci-release](https://github.com/sbt/sbt-ci-release/tree/main#github-actions) repo.
High level overview:
* Each PR merged to main triggers the [release-drafter](https://github.com/marketplace/actions/release-drafter) workflow which creates a draft release and/or adds a link to the PR under a changes section.
* When we are ready to release, publish the draft which will push tags to the main repo.
* The Maven Release workflow triggers when tags are pushed to main, which publishes
* Ran the Maven publish workflow targeting my branch: https://github.com/Topl/BramblSc/actions/runs/4813348677
I can't test the release drafter workflow since it requites the …

[BN-997]: TDSK Deployment Tooling

---

brambl-sdk/src/main/scala/co/topl/brambl/validation/TransactionCostCalculatorInterpreter.scala
brambl-sdk/src/main/scala/co/topl/brambl/validation/algebras/TransactionCostCalculator.scala
brambl-sdk/src/test/scala/co/topl/brambl/validation/TransactionCostCalculatorInterpreterSpec.scala

- Some transactions are “harder” to validate than others.  In particular, transactions which spend a lot of inputs, produce a lot of outputs, or use complicated contracts may take a lot more CPU/memory/bandwidth to evaluate than a simple transfer.
- A function should exist which estimates how hard it would be to include a given transaction in the blockchain.
- Create TransactionCostCalculator and TransactionCostCalculatorInterpreter
- Estimate cost of a Transaction based on its immutable bytes, difficulty of input proofs, and number of outputs
- Create initial set of cost estimates for proof types
- New basic unit tests
- #BN-900

Implement TransactionCostCalculator

---

brambl-sdk/src/main/scala/co/topl/brambl/builders/BuilderError.scala
brambl-sdk/src/main/scala/co/topl/brambl/builders/TransactionBuilderInterpreter.scala
brambl-sdk/src/main/scala/co/topl/brambl/dataApi/DataApi.scala
brambl-sdk/src/main/scala/co/topl/brambl/wallet/CredentiallerInterpreter.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockDataApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockHelpers.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/CredentiallerInterpreterSpec.scala

Previously the Credentialler was under the assumption that indices (x/y/z) were associated to a UTXO. We know now that this is not the case as indices are associated to a Key Pair which can map to one or more SignaturePropositions and a UTXO's lock may contain many SignaturePropositions.
This PR contains changes to Credentialler, TransactionBuilder, and DataApi. At a high level, instead of the Credentialler retrieving the indices for a utxo, the Credentialler will retrieve the individual secrets needed for each proposition.
Specifically: 
- A SignatureProposition will map to Indices in the DataApi
- A DigestProposition will map to a Preimage in the DataApi
DataApi was updated to include functions to support this:
- Remvoed `getIndicesByTxoAddress`  since a UTXO/STXO is not directly …

TSDK-460: Update how Credentialler retrieves information

---

brambl-sdk/src/main/scala/co/topl/brambl/builders/TransactionBuilderInterpreter.scala
brambl-sdk/src/main/scala/co/topl/brambl/syntax/TransactionSyntax.scala
brambl-sdk/src/main/scala/co/topl/brambl/syntax/package.scala
brambl-sdk/src/main/scala/co/topl/brambl/wallet/CredentiallerInterpreter.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockHelpers.scala
brambl-sdk/src/test/scala/co/topl/brambl/generators/ModelGenerators.scala
brambl-sdk/src/test/scala/co/topl/brambl/syntax/TransactionSyntaxSpec.scala
project/Dependencies.scala

- The IoTransaction message now includes a transactionId field
- This PR adds helpers for populating that field
- TransactionSyntax ops helper
- New unit tests for TransactionSyntax
- #BN-995

TransactionSyntax ID 

---

brambl-sdk/src/main/scala/co/topl/brambl/wallet/CredentiallerInterpreter.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockHelpers.scala
brambl-sdk/src/test/scala/co/topl/brambl/common/ContainsSignableSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/validation/TransactionCostCalculatorInterpreterSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/CredentiallerInterpreterSpec.scala

Previously the credentialler overides the existing proofs in a transaction that it is attempting to prove. This prevents any multi-participant usage since after the first participant proves the transaction (into a partially proven transaction), the proofs from participant 1 would get erased when participant 2 goes to prove the partially proven transaction. This PR adds support for keeping any existing valid proofs in the transaction and will only prove a proposition if it was not previously proven.
- When proving a proposition, supply the existing proof from the attestation. If it is invalid (not the same type or empty) then we will generate a new proof and return that. Else, return the existing proof
- Broke and modularized `getProof` into multiple smaller functions (one for each type of …

TSDK-474 Support for proving already partially proven transactions

---

brambl-sdk/src/main/scala/co/topl/brambl/codecs/AddressCodecs.scala
brambl-sdk/src/test/scala/co/topl/brambl/codecs/AddressCodecsSpec.scala

While doing testing with Fernando we found a bug where the newtwork and ledger Id were not correctly decoded.
The bug was fixed
The unit tests were not checking for that and were corrected.
* No ticket created, the fix took less than 5 minutes.

Bug address decoder

---

brambl-sdk/src/main/scala/co/topl/brambl/builders/locks/LockTemplate.scala
brambl-sdk/src/main/scala/co/topl/brambl/builders/locks/PropositionTemplate.scala
brambl-sdk/src/main/scala/co/topl/brambl/codecs/LockTemplateCodecs.scala
brambl-sdk/src/main/scala/co/topl/brambl/codecs/PropositionTemplateCodecs.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockHelpers.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/locks/LockTemplateSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/locks/PropositionTemplateSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/codecs/LockTemplateCodecsSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/codecs/PropositionTemplateCodecsSpec.scala

The y layer of the cartesian indexing scheme represents Contract/Lock Templates. These templates must be deterministic and portable to support the ability of sharing across participants. This PR adds the ability to define a new Lock (or proposition) template as well as the ability to instantiate a new instance by providing a list of VerificationKeys (which should map to the x layer of the cartesian indexing).
- Added the ability to create Proposition Templates. Proposition Templates generally will not be used by the clients themselves; instead, they will create a Lock Template which contains Proposition templates within it. The following Proposition Templates are possible to be created:
- Locked
- Height
- Tick
- Digest
- Signature
- And
- Or
- Not
- Threshold
- Added the ability to …

TSDK-479 Implemented Lock and Proposition Templates

---

brambl-sdk/src/main/scala/co/topl/brambl/dataApi/DataApi.scala
brambl-sdk/src/main/scala/co/topl/brambl/wallet/CredentiallerInterpreter.scala
brambl-sdk/src/main/scala/co/topl/brambl/wallet/WalletStateAlgebra.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockDataApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockWalletStateApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/CredentiallerInterpreterSpec.scala

API definitions for the functions to track wallet state should be migrated to BramblSc from brambl-cli since they will be required by other components in BramblSc. For ex, Credentialler, TransactionBuilder (in TSDK-489), LockBuilder (in TSDK-482), etc.
- Migrated the WalletStateAlgebra trait from brambl-cli to BramblSc. Added scaladoc
- Added 4 additional functions for tracking x and y entries; Add and get entities (verification keys) + add and get lock templates
- Moved getIndices and getPreimage to  WalletStateAlgebra  from DataApi
- Credentialler now takes in WalletStateAlgebra  and WalletApi instead of DataApi since it no longer requires the latter
- Updated the Credentialler tests to align with the changes
- Ran `checkPR` and ensured was successful
* Part of TSDK-480
* Part of …

TSDK-480 Added WalletStateAlgebra from brambl-cli

---

.github/workflows/maven_release.yml
build.sbt
project/Dependencies.scala

In preparation to deploy BramblSc to maven, some changes were made.
The tooling was already added in https://github.com/Topl/BramblSc/pull/50 , however this PR contains minor changes; prefixing `sonatypeCredentialHost` with `ThisBuild / ` and the `https://s01.oss.sonatype.org/content/repositories/releases/` resolver.
Additionally, the Topl dependencies (protobuf-specs and quivr4s) were also updated from jitpack to the released Maven artifacts. 
- ensured released Topl dependencies from Maven are being used
- ran unit tests in both projects and ensured successful (sanity)
- ran `sbt checkPR` and ensured successful (sanity)
- ran `sbt publishLocal` and ensured successful (sanity)
The deployment will be tested after this PR is merged in and the 2.0.0-alpha1 tag is pushed
* TSDK-496

TSDK-496 Prepare to Deploy to Maven

---

brambl-sdk/src/main/scala/co/topl/brambl/codecs/PropositionTemplateCodecs.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockHelpers.scala

There was a bug in Locked Proposition templates where instead of storing the value of the Locked data, we stored the string representation of the bytestring.
In addition, the digest within the Digest Proposition Template was not human readable.
- For encoding Locked to JSON, instead of using `a.data.get.value.toString`, we use `encodeToBase58(a.data.get.value.toByteArray)`
- For decoding Locked from JSON, we `decodeFromBase58` and then convert the decoded data into Locked Proposition. If decoding the data fails, we use a Custom Decoding (circe's DecodingFailure) reason
- For encoding Digest to JSON, instead of using `Strings.fromByteArray`, we use `encodeToBase58`
- For decoding Digest from JSON, we parse the digest value then `decodeFromBase58`. If successful we convert the decoded data …

TSDK-530 Minor fixes to Locked and Digest Proposition Templates

---

README.md

- In addition to Jitpack, BramblSc can be consumed via maven releases. The README should be updated to reflect that
- This will serve as a test to https://github.com/Topl/BramblSc/pull/77
- updated README.md
n/a
* No ticket
* Tests TSDK-507

Updated README.md with updated consumption instructions

---

build.sbt
project/Dependencies.scala

Update quivr4s to 2.0.0-alpha2
Update quivr4s dependency.
Update quivr4s dependency.
N/A
* Updated for release as part of ticket TSDK-470

Update quivr4s to 2.0.0-alpha2

---

brambl-sdk/src/main/scala/co/topl/brambl/dataApi/ContractStorageAlgebra.scala
brambl-sdk/src/main/scala/co/topl/brambl/dataApi/PartyStorageAlgebra.scala
brambl-sdk/src/main/scala/co/topl/brambl/dataApi/WalletKeyApiAlgebra.scala
brambl-sdk/src/main/scala/co/topl/brambl/wallet/WalletApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockWalletKeyApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/WalletApiSpec.scala
build.sbt
project/Dependencies.scala
service-kit/src/main/scala/co/topl/brambl/servicekit/ContractStorageApi.scala
service-kit/src/main/scala/co/topl/brambl/servicekit/PartyStorageApi.scala
service-kit/src/main/scala/co/topl/brambl/servicekit/WalletKeyApi.scala
service-kit/src/main/scala/co/topl/brambl/servicekit/WalletStateApi.scala
service-kit/src/main/scala/co/topl/brambl/servicekit/WalletStateResource.scala
service-kit/src/test/scala/co/topl/brambl/servicekit/BaseSpec.scala
service-kit/src/test/scala/co/topl/brambl/servicekit/ContractStorageApiSpec.scala
service-kit/src/test/scala/co/topl/brambl/servicekit/PartyStorageApiSpec.scala
service-kit/src/test/scala/co/topl/brambl/servicekit/WalletKeyApiSpec.scala
service-kit/src/test/scala/co/topl/brambl/servicekit/WalletStateApiSpec.scala

Add the service kit implementation. This kit provides a base implementation of the WalletKeyApi (persisting to disk), PartyStorageApi, ContractStorageApi, and WalletStateApi (latter 3 using sqlite).
- Migrate the bulk of the implementation from brambl-cli; traits in brambl-sdk and interpreters in the service kit
- Made additions to WalletKeyApi (previously update and delete were not implemented)
- Updated WalletApi in brambl-sdk: Added save mnemonic functionality, and removed older stubs for wallet recovery that will not exist in brambl-sdk
- Wrote tests
- Wrote tests for each of the APIs
- Ensured all existing tests pass
- Consumed this package in brambl-cli
* Closes TSDK-532

TSDK-532 Scala Service Kit Implementation

---

brambl-sdk/src/main/scala/co/topl/brambl/dataApi/WalletStateAlgebra.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockWalletStateApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/CredentiallerInterpreterSpec.scala
build.sbt
service-kit/src/main/scala/co/topl/brambl/servicekit/WalletStateApi.scala
service-kit/src/test/scala/co/topl/brambl/servicekit/BaseSpec.scala
service-kit/src/test/scala/co/topl/brambl/servicekit/ContractStorageApiSpec.scala
service-kit/src/test/scala/co/topl/brambl/servicekit/PartyStorageApiSpec.scala
service-kit/src/test/scala/co/topl/brambl/servicekit/WalletStateApiSpec.scala

The goal of this PR is to remove the network id where not necessary.
We require new parameters for some methods of the WalletStateAlgebra so that we do not need the transactionApi as a dependency.
The tests were fixed.
* TSDK-532

TSDK-532 Remove reference to network id where not necessary

---

brambl-sdk/src/main/scala/co/topl/brambl/utils/CatsUnsafeResource.scala
brambl-sdk/src/main/scala/co/topl/brambl/wallet/WalletApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockHelpers.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockWalletKeyApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockWalletStateApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/utils/CatsUnsafeResourceSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/CredentiallerInterpreterSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/WalletApiSpec.scala
build.sbt

there is a [flaky test in the wallet API](https://github.com/Topl/BramblSc/actions/runs/5809330070/job/15747898079#step:8:271) that fails with parallel execution
Instead of using implicit ExtendedEd25519, use a CatsUnsafeResource queue to manage its use.
Note: Adding CatsUnsafeResource (and updating WalletApi_ was a small change, most of the changes in this PR is updating the tests to align with the changes to WalletApi (Replacing Id[_] with IO[_]).
- Ran tests locally 20x in a row with parallel execution => flaky test did not fail
- Ran tests locally 20x in a row without parallel execution => flaky test did not fail
- Temporarily updated the dependencies in bifrost and ensured all checks pas
- Locally updated the dependencies in brambl-cli and ensured all the unit tests pass
* TSDK-550
* …

TSDK-572 Address WalletApi flaky test with CatsUnsafeResource

---

brambl-sdk/src/main/scala/co/topl/brambl/builders/BuilderError.scala
brambl-sdk/src/main/scala/co/topl/brambl/builders/TransactionBuilderApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSpec.scala

Add capability to TransactionBuilder to create a Series Minting transaction.
- Added function `buildSimpleSeriesMintingTransaction` which mirrors buildSimpleGroupMintingTransaction from https://github.com/Topl/BramblSc/pull/99 for Group Constructor minting.
- Added Tests
- Modified `validateGroupMintingParams` to `validateConstructorMintingParams` since these parameter validations are identical for the 2 functions.
- (somewhat unrelated) removed object BuilderError since its not used anywhere in the builders package
- added new tests
- ensured all existing tests pass
* closes TSDK-569

TSDK-569 Series Constructor Minting Transaction

---

brambl-sdk/src/main/scala/co/topl/brambl/builders/TransactionBuilderApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSpec.scala
project/Dependencies.scala

Added the ability to create a transaction to mint TAMv2 Asset tokens
- Added new function signature `buildSimpleAssetMintingTransaction`
- Refactored the User Input validations to reduce code reuse (certain validations are common). Note that validating the metadata is a nice-to-have and will be implemented in a future ticket (TSDK-585)
- Added tests
- updated the existing tests for minting Group and Series constructor tokens to align with the changes to User input validation
- Ensured all existing tests pass
- Identified and added 18 new test cases for asset minting. These cover both success and failure cases.
* Closes TSDK-570

TSDK-570 Add Asset minting to Transaction builder

---

brambl-sdk/src/main/scala/co/topl/brambl/syntax/BoxValueSyntax.scala
brambl-sdk/src/main/scala/co/topl/brambl/syntax/Int128Syntax.scala
brambl-sdk/src/main/scala/co/topl/brambl/syntax/package.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockHelpers.scala
brambl-sdk/src/test/scala/co/topl/brambl/syntax/BoxValueSyntaxSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/syntax/Int128SyntaxSpec.scala

Added Box.Value and Int128 syntax ops to reduce the level of verbosity 
Added Box.Value (Value.Value.types -> Value, Value -> quantity, Value -> ValueTypeIdentifier) and Int128 (BigInt <-> Int128, long -> Int128) syntax ops
TBD
* Added as part of TSDK-578 work

TSDK-578 Added Syntax Ops for  Box.Value and Int128

---

brambl-sdk/src/main/scala/co/topl/brambl/builders/BuilderError.scala
brambl-sdk/src/main/scala/co/topl/brambl/builders/TransactionBuilderApi.scala
brambl-sdk/src/main/scala/co/topl/brambl/builders/UserInputValidations.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSpec.scala

Transfer tokens while considering different token types. Specifically, The user can transfer X amount of a specific type of token to a recipient address while providing ALL tokens at the same LockAddress. Any tokens not going to the recipient will go to a change address
- Added `buildLvlTransferTransaction`, `buildGroupTransferTransaction`, `buildSeriesTransferTransaction`, and `buildAssetTransferTransaction` to the Transaction Builder API
- All 4 of these functions under-the-hood will use private function `buildTransferTransaction` which handles the actual implementation (and takes in addition a `ValueTypeIdentifier` to specify which token is meant to be transferred to the recipient)
- At a high level, this function 
- Expects all provided Txos to correspond with the provided …

TSDK-578 Transfer Tokens

---

brambl-sdk/src/main/scala/co/topl/brambl/wallet/CredentiallerInterpreter.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/CredentiallerInterpreterSpec.scala

Signature validation was failing due to the transaction signature changing after using the Credentialler to prove a transaction. The cause was that we were stripping all other fields (other than inputs, outputs, and datum) on the transaction. This was not caught before since we previously did not have any other fields on a transaction. The issue arose since we are now introducing Policies and Statements into the Tx.
Instead of recreating the Proven Transaction using IoTransaction.defaultinstance (and populating some fields), we copy the unproven transaction and only override the inputs.
- Ensured existing tests pass
- Added a new test case to check preserving fields
* N/a

Quick Fix: Preserve Transaction fields in Credentialler

---

brambl-sdk/src/main/scala/co/topl/brambl/validation/TransactionSyntaxInterpreter.scala
brambl-sdk/src/test/scala/co/topl/brambl/validation/TransactionSyntaxInterpreterAssetSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/validation/TransactionSyntaxInterpreterMintingCaseASpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/validation/TransactionSyntaxInterpreterRuleBSpec.scala

Well-formedness
-  A. For each Group: input group + minted group == total ouputs group
-  validate that groups are never burned
https://topl.atlassian.net/wiki/spaces/LABS/pages/678658061/Validation+TAMv2+Transactions+-+Meeting+Fernando+Edmundo+2023-09-08
preparePr
*BN-1229

BN-1229 groupEqualFundsValidation

---

brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterAssetTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterGroupTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterLvlsTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSeriesTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSpecBase.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterTransferAllSpec.scala

To make transaction builder tests more readable and maintainable; give readers of the code more visibility/understanding the different test cases.  This specifically affects the tests for `buildTransferAmountTransaction` and `buildTransferAllTransaction`
No new tests were added. This is simply refactoring how some of the existing tests are written.
As of https://github.com/Topl/BramblSc/pull/125 , there are 24 tests for `buildTransferAllTransaction` and 33 tests for `buildTransferAmountTransaction` where we test different combinations of parameters while calling the functions.
As is, it is very hard for someone who is unfamiliar with the code to understand what the different test cases are testing. Two main reasons for this
- it is unclear which parameter(s) is being changed across tests …

Test Cleanup part 2

---

brambl-sdk/src/test/scala/co/topl/brambl/MockHelpers.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/AggregationOpsSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterAssetTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterGroupTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterLvlsTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSeriesTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSpecBase.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterTransferAllSpec.scala

Ensure we support Fractionable Assets in `buildTransferAllTransaction`.
Mirrors https://github.com/Topl/BramblSc/pull/124 but for Immutable assets.
Existing implementation already supports. This PR adds/updates tests to ensure this.
- update Mock Data to also include immutable assets (group and series, group only, and series only fungible)
- Updated existing tests to consider the new mock data
- added new tests for buildTransferAllTransaction when immutable assets are identified to transfer
ensure all tests pass
* closes TSDK-598

TSDK-597 Support Immutable Assets in buildTransferAllTransaction

---

brambl-sdk/src/test/scala/co/topl/brambl/MockHelpers.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/AggregationOpsSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterAssetTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterGroupTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterLvlsTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSeriesTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSpecBase.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterTransferAllSpec.scala

Ensure we support Fractionable Assets in `buildTransferAllTransaction`. 
Existing implementation already supports. This PR adds/updates tests to ensure this.
- update Mock Data to also include fractionable assets (group and series, group only, and series only fungible)
- Updated existing tests to consider the new mock data
- added new tests for `buildTransferAllTransaction` when fractionable assets are identified to transfer
ensure all tests pass
* closes TSDK-598

TSDK-598 Support Fractionable Assets in buildTransferAllTransaction

---

brambl-sdk/src/main/scala/co/topl/brambl/validation/TransactionSyntaxInterpreter.scala
brambl-sdk/src/test/scala/co/topl/brambl/validation/TransactionSyntaxInterpreterAssetSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/validation/TransactionSyntaxInterpreterMintingCaseASpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/validation/TransactionSyntaxInterpreterRuleBSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/validation/TransactionSyntaxInterpreterTransferSeriesSpec.scala

SeriesEqualFundsValidation
*  - Check Moving Series Tokens: Let s be a series identifier, then the number of Series Constructor Tokens with group identifier s in the input is equal to the number of the number of Series Constructor Tokens with identifier s in the output.
*  - Check Minting Constructor Tokens: Let s be a series identifier and p the series policy whose digest is equal to s, all of the following statements are true:
*   -  The policy p is attached to the transaction.
*   - The number of series constructor tokens with identifiers in the output of the transaction is strictly bigger than 0.
*   -  The registration UTXO referenced in p is present in the inputs and contains LVLs.
fix unit test
BN 1230

BN-1230 series transfer validation

---

service-kit/src/main/scala/co/topl/brambl/servicekit/WalletStateApi.scala

Fix a bug that appeared in Brambl-cli
The result of the query to the database was returning null and it was not being transformed into a `None`. We fixed that problem.
It was tested in Brambl-CLI.
* TSDK-608

TSDK-608 Fix bug WalletStateApi.getLockByIndex

---

.github/workflows/deploy_docs.yml
brambl-sdk/src/main/scala/co/topl/brambl/builders/AggregationOps.scala
brambl-sdk/src/main/scala/co/topl/brambl/builders/TransactionBuilderApi.scala
brambl-sdk/src/main/scala/co/topl/brambl/builders/UserInputValidations.scala
brambl-sdk/src/main/scala/co/topl/brambl/syntax/BoxValueSyntax.scala
brambl-sdk/src/main/scala/co/topl/brambl/syntax/TokenTypeIdentifierSyntax.scala
brambl-sdk/src/main/scala/co/topl/brambl/validation/TransactionSyntaxInterpreter.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockHelpers.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/AggregationOpsSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSpecBase.scala
brambl-sdk/src/test/scala/co/topl/brambl/syntax/TokenTypeIdentifierSyntaxSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/validation/TransactionSyntaxInterpreterAssetSpec.scala
documentation/docs/reference/transactions/transfer.mdx

Simplify the ValueTypeIdentifier definitions for the users. When using the TransactionBuilder users shouldn't need to specify unnecessary fields; only the IDs.
- updated ValueTypeIdentifier  definition for Asset Types; they no longer include QuantityDescriptor and are not separated by fungibility types.
- updated tx builder's parameter validation to check Quantity descriptor type via the Value instead of type identifier
- Added updated TransactionSyntaxValidation to reflect change (to ensure asset outputs have the correct fields)
- Added 4 new validation tests to ensure TransactionSyntaxValidation behaves as expected
- updated brambl-cli; ensured integration tests successful
- updated node and ensured actions were successful
* TSDK-612

TSDK-612 Simplify ValueTypeIdentifier

---

brambl-sdk/src/main/scala/co/topl/brambl/builders/AggregationOps.scala
brambl-sdk/src/main/scala/co/topl/brambl/builders/TransactionBuilderApi.scala
brambl-sdk/src/main/scala/co/topl/brambl/builders/UserInputValidations.scala
brambl-sdk/src/main/scala/co/topl/brambl/syntax/BoxValueSyntax.scala
brambl-sdk/src/main/scala/co/topl/brambl/syntax/TokenTypeIdentifierSyntax.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockHelpers.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/AggregationOpsSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterAssetMintingSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterAssetTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterGroupMintingSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterGroupTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterLvlsTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSeriesMintingSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSeriesTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSpecBase.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterToplTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterTransferAllSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/syntax/BoxValueSyntaxSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/syntax/TokenTypeIdentifierSyntaxSpec.scala
documentation/docs/reference/transactions/transfer.mdx

Transfer functions in TransactionBuilder failed when TOPLs or UpdateProposals were passed in as parameters. The SDK was updated to support such parameters.
- For UpdateProposals (and any new types that may be added to the ecosystem in the future), added ValueTypeIdentifier "UnknownType". If an "UnknownType" is provided as a parameter (either in TXOs or as tokenIdentifier) in TxBuilder functions, a validation error message will be returned.
- Support Transferring TOPLs; transferAll supports all TOPLs whereas transferAmount supports all TOPLs in the txos but only TOPLs without staking registration for tokenIdentifier (since as a default we won't aggregate/deaggregate for the user).
- Added tests
- Added new tests for ValueTypeIdentifier, Aggreations, and TransactionBuilder
- Ensured all …

TSDK-610 Add Support for TOPLs and new unknown types (UpdateProposals) in TransactionBuilder

---

.github/workflows/_sbt_build.yml
.github/workflows/deploy_docs.yml
.github/workflows/maven_release.yml
.github/workflows/pr.yml
build.sbt

- readded `+test` to `preparePR`. I verified that it works on my machine when using WSL
- updated GH Actions workflows such that maven release and GH Pages do not run unless build/test succeeds. Update to documentation portal will only occur if we are pushing to main
- Added Publish Test Results
- Added GH Deployments for releases (tag pushes) and snapshots (branch pushes)
For push to any branch:
https://github.com/Topl/BramblSc/actions/runs/6893972552
For push to main; I will manually check that the workflow ran properly once merged. Should be similar to any branch
For tags; I will manually check that the workflow ran properly once a release is created. Should deploy pages and deploy to releases 
* closes TSDK-637

TSDK-637 Workflow dependencies

---

brambl-sdk/src/main/scala/co/topl/brambl/builders/TransactionBuilderApi.scala
brambl-sdk/src/main/scala/co/topl/brambl/builders/UserInputValidations.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterAssetMintingSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterAssetTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterGroupMintingSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterGroupTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterLvlsTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSeriesMintingSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSeriesTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterToplTransferSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterTransferAllSpec.scala
documentation/docs/reference/prove.mdx
documentation/docs/reference/rpc.mdx
documentation/docs/reference/transactions/transfer.mdx

If the input parameter `txos` (in TransactionBuilder functions) contain an UnknownType parameter, filter it out instead of sending an error.
The reason for this change is that when spending from Genesis, there will always be an UpdateProposal value, thus always erroring out (forcing users to manually filter them out before hand). This became apparent when writing examples in the Documentation portal; for example
```
txos <- genusQuery.queryUtxo(fromAddr)
fromTxos = txos.filter(_.transactionOutput.value.value.typeIdentifier != UnknownType) // <-- this line
res <- transactionBuilderApi.buildTransferAllTransaction(fromTxos, fromLock.getPredicate, toAddr, toAddr, 1L)
```
- Allowed UnknownType to be provided and filter it out within the function (instead of expecting the user to do it before …

TSDK-638 Filter out UnknownType

---

brambl-sdk/src/main/scala/co/topl/brambl/builders/TransactionBuilderApi.scala
documentation/docs/reference/transactions/minting.mdx

To document a working example to illustrate how users can use the SDK to mint Group, Series, and Asset tokens
- Added Examples to the documentation portal
- Very minor change to the code (default Option parameters to None)
Ensured the new examples all work standalone locally 
* closes TSDK-652

TSDK-652 Added minting examples

---

brambl-sdk/src/main/scala/co/topl/brambl/dataApi/BifrostQueryAlgebra.scala
brambl-sdk/src/main/scala/co/topl/brambl/dataApi/BifrostQueryInterpreter.scala
service-kit/src/main/scala/co/topl/brambl/servicekit/WalletStateApi.scala

As part of improving the usability of the CLI, we implemented full validation at broadcast time. This  validation requires to know the current height of the block and the current tick. Although this functionality is implemented in the node, the brambl-sdk did not support it. We implemented it in order to add the validation to the CLI.
We implemented it by following the same pattern as before.
All tests continue to pass.
* TSDK-641

TSDK-641 Usability Improvements for CLI (get block by depth)

---

CHANGELOG.md
documentation/docs/reference/wallets/create.mdx
documentation/docs/reference/wallets/import.mdx
documentation/docs/reference/wallets/usage.mdx

To document the wallet functionality that use persistence (WalletKeyApi). These include persisting a created wallet: `createAndSaveNewWallet`, `importWalletAndSave`, as well as using a persisted wallet: `loadAndExtractMainKey`
Documented the 3 functions as 3 use cases under "Wallet Keys" in the documentation portal
No code changes, but ensured all examples run successfully 
* closes TSDK-646

TSDK-646 Document Additional Wallet Functions

---

documentation/docs/reference/broadcast.mdx
documentation/docs/reference/locks/build-lock.mdx
documentation/docs/reference/locks/create-lock-addr.mdx
documentation/docs/reference/locks/create-template.mdx
documentation/docs/reference/locks/locks.mdx
documentation/docs/reference/locks/share-lock-addr.mdx
documentation/docs/reference/locks/share-template.mdx
documentation/docs/reference/prove.mdx
documentation/docs/reference/rpc.mdx
documentation/docs/reference/transactions/minting.mdx
documentation/docs/reference/transactions/transactions.mdx
documentation/docs/reference/transactions/transfer.mdx
documentation/docs/reference/wallet-state.mdx
documentation/docs/reference/wallets/create.mdx
documentation/docs/reference/wallets/import.mdx
documentation/docs/reference/wallets/usage.mdx
documentation/docs/service-kit/usage.md
documentation/src/css/custom.css

Document Update Wallet State & tie-in wallet state with the rest of the Reference Documentation
- minor updates to existing code examples to include line-highlighting. Since the code examples contain all necessary needed to run, the specific line that is being demonstrated is highlighted.
- Added example + documentation for update wallet state under "Service Kit > Usage"
- Under "Reference > Wallet State" added information for initializing and updating wallet state. This links to the sections under "Service Kit". 
- Added a blurb under "Reference > Build Lock" to indicate that they should update wallet state
Ensured all examples worked locally
* closes TSDK-645

TSDK-645 Document [Update] Wallet State

---

CHANGELOG.md
documentation/docs/reference/getting-started.mdx
documentation/docs/tutorials/tutorials/_category_.json
documentation/docs/tutorials/tutorials/obtain-funds.md
documentation/docs/tutorials/tutorials/simple-transfer.md
documentation/docs/tutorials/tutorials/tutorial1.md
documentation/docs/tutorials/tutorials/tutorial2.md
documentation/docs/tutorials/tutorials/tutorial3.md
documentation/docs/tutorials/tutorials/tutorials.mdx
documentation/docusaurus.config.js
service-kit/src/main/scala/co/topl/brambl/servicekit/WalletStateResource.scala

To begin documenting tutorials
- Displayed the "Tutorials" section on the portal
- Added 2 tutorials: Load New Wallet with funds from Genesis, Transfer from one wallet to another
- Minor code change to `WalletStateResource`. This is since, without this change, I was unable to re-run code examples multiple times on my machine (the driver appears to get de-registered) and I had to keep restarting my machine. 
- Ensured all existing unit tests pass
- Ensured all added standalone examples (i.e., "Breakpoint Check" and "Putting it all together" sections) work locally
- Ensured `npm run build` and `npm run serve` are succesul (i.e, no broken links)
* Closes TSDK-647

TSDK-647 Load Wallet Tutorial & Transfer to another Wallet Tutorial

---

CHANGELOG.md
brambl-sdk/src/main/scala/co/topl/brambl/dataApi/WalletStateAlgebra.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockWalletStateApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/CredentiallerInterpreterSpec.scala
documentation/docs/reference/locks/create-template.mdx
documentation/docs/reference/wallet-state.mdx
service-kit/src/main/scala/co/topl/brambl/servicekit/WalletStateApi.scala
service-kit/src/test/scala/co/topl/brambl/servicekit/WalletStateApiSpec.scala

To add the ability to use and prove Digest propositions.
- Added `addPreimage` for a digest proposition in the Service Kit
- Implemented `getPreimage`
- The above 2 points involved adding a new table
- Updated documentation
- Added a unit test for `addPreimage` which tests adding and retrieving
- ensured all other unit tests pass
- Used the changes in brambl-cli; ensured all unit tests and integration tests pass
* closes TSDK-665

TSDK-665 Added support for proving digests propositions

---

CHANGELOG.md
brambl-sdk/src/main/scala/co/topl/brambl/dataApi/WalletStateAlgebra.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockWalletStateApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/CredentiallerInterpreterSpec.scala
documentation/docs/reference/wallet-state.mdx
documentation/docs/service-kit/usage.md
documentation/docs/tutorials/tutorials/mint-asset.md
documentation/docs/tutorials/tutorials/obtain-funds.md
documentation/docs/tutorials/tutorials/simple-transfer.md
service-kit/src/main/scala/co/topl/brambl/servicekit/WalletStateApi.scala
service-kit/src/test/scala/co/topl/brambl/servicekit/FellowshipStorageApiSpec.scala
service-kit/src/test/scala/co/topl/brambl/servicekit/TemplateStorageApiSpec.scala
service-kit/src/test/scala/co/topl/brambl/servicekit/WalletStateApiSpec.scala

Ease of use improvement for using `initWalletState`.  Now users do not have to do a (x=1,y=1) partial derivative of their Topl Main key pair before initializing a wallet state.
- Updated Signature of the function to take in a KeyPair (needed for partial derivation).
- Updated Service Kit to perform the partial derivation within the `initWalletState` function
- Updated all callers (tests) to use the updated parameter
- Updated documentation to use the updated parameter
- Ensure all tests pass
- Ensure all documentation examples run successfully. Note: The code examples within "Service Kit > Usage" are not directly runnable using `scala-cli` *yet*. This is because it depends on a released version of the SDK. These changes are not yet released but will be a part of `beta2` (which is what the …

TSDK-666 initWalletState parameter improvement

---

README.md
brambl-sdk/src/main/scala/co/topl/brambl/display/AssetDisplayOps.scala
brambl-sdk/src/main/scala/co/topl/brambl/display/BlockDisplayOps.scala
brambl-sdk/src/main/scala/co/topl/brambl/display/GroupDisplayOps.scala
brambl-sdk/src/main/scala/co/topl/brambl/display/SeriesDisplayOps.scala
brambl-sdk/src/main/scala/co/topl/brambl/display/StructDisplayOps.scala
brambl-sdk/src/main/scala/co/topl/brambl/display/StxoDisplayOps.scala
brambl-sdk/src/main/scala/co/topl/brambl/display/TransactionDisplayOps.scala
brambl-sdk/src/main/scala/co/topl/brambl/display/UtxoDisplayOps.scala
brambl-sdk/src/main/scala/co/topl/brambl/display/ValueDisplayOps.scala
brambl-sdk/src/main/scala/co/topl/brambl/display/package.scala
brambl-sdk/src/test/scala/co/topl/brambl/display/DisplaySpec.scala

To add Pretty Print capabilities (allow users to Display) a transaction using the SDK
The structure and display format already existing in brambl-cli. This PR refactors the code
-  Added a display package to the SDK
- Refactored the `display` functions to be accessible using `.display`. This aligns with our `ContainsImmutable` and `ContainsEvidence` pattern
- Added a test with a complex transaction to the unit tests
- Ensured nothing in brambl-cli broke using this (see brambl-cli's PR)
* TSDK-663

TSDK-663 Transaction Pretty Print / Display

---

CHANGELOG.md
brambl-sdk/src/main/scala/co/topl/brambl/Context.scala
brambl-sdk/src/main/scala/co/topl/brambl/validation/Sha256DigestInterpreter.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockHelpers.scala
brambl-sdk/src/test/scala/co/topl/brambl/MockWalletStateApi.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/locks/PropositionTemplateSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/wallet/CredentiallerInterpreterSpec.scala
documentation/docs/reference/locks/create-template.mdx

With the upcoming BTC bridge, we need to support Sha256 Digest propositions in our ecosystem (so the preimages and digests are cross compatible with bitcoin). This PR adds this support.
- Propositions themselves are routine-agnostic, so no changes were needed to the quivr package
- We already have a Sha256 implementation, so no changes were needed to the crypto package
- In brambl-sdk, added a Sha256DigestInterpreter which validates a given Digest and Preimage using the Sha256 routine.
- In brambl-sdk, added the "Sha256" routine to `hashingRoutines` in the Context object; this routine uses the newly created Sha256DigestInterpreter, allowing the quivr verifier to validate for any Digest propositions using a "Sha256" routine.
-  In the docs, we now list the possible values for `routine` …

TSDK-729 Support for Sha256 Digest Locks

---

brambl-sdk/src/main/scala/co/topl/brambl/utils/CatsUnsafeResource.scala
brambl-sdk/src/main/scala/co/topl/brambl/validation/TransactionAuthorizationInterpreter.scala
brambl-sdk/src/main/scala/co/topl/brambl/validation/TransactionCostCalculatorInterpreter.scala

- CatsUnsafeResource usually wraps cryptographic routines, which are generally CPU-intensive
- CPU-intensive calls should be wrapped in `Async[F].cede` to prevent starvation
- Unrelated: Fixed Match warnings in TransactionCostCalculator and TransactionAuthorizationInterpreter
- Unrelated: Noticed logic error in TransactionAuthorizationInterpreter that would only validate the _last_ input of a transaction
- Modify CatsUnsafeResource implementation to `cede` before and after the Resource allocation.  Also `cede` after resource initialization
- Add case statements for empty attestation
- Modify TransactionAuthorizationValidation to use `.foldLeftM` instead of `foldLeft` to account for the F-context.  If `Left` is found, short-circuit.
- `preparePR`
- Tested in Bifrost's NodeAppTest
- …

CatsUnsafeResource Use cede

---

brambl-sdk/src/main/scala/co/topl/brambl/monitoring/BifrostMonitor.scala
integration/src/test/scala/co/topl/brambl/monitoring/BifrostMonitorTest.scala
service-kit/project/build.properties

Finish up Bifrost block monitoring. This change adds reporting of existing blocks (given a start BlockId). This mirrors the Bitcoin Monitoring.
- Utilized the startBlock parameter in the BifrostMonitor constructor
- To the beginning of the monitoring stream, add retroactively queried blocks. 
Added an integration test
* Closes TSDK-787

TSDK-787 Bifrost Monitoring - Retroactive reporting

---

CHANGELOG.md
brambl-sdk/src/main/scala/co/topl/brambl/monitoring/BifrostMonitor.scala

Address warning that appears when using the Bifrost monitor
```
[WARNING] Your app's responsiveness to a new asynchronous event (such as a new connection, an upstream response, or a timer) was in excess of 100 milliseconds. Your CPU is probably starving. Consider increasing the granularity of your delays or adding more cedes. This may also be a sign that you are unintentionally running blocking I/O operations (such as File or InetAddress) without the blocking combinator.
```
Replace `Stream.fromIterator` with `Stream.fromBlockingIterator`
(manual)
Ran the bifrost monitor for a long period of time, previously , the warning would appear. I have not encountered the warning since
* n/a

Hot fix: Fix responsiveness warning

---

.github/workflows/_sbt_build.yml
CHANGELOG.md
brambl-sdk/src/main/scala/co/topl/brambl/monitoring/BitcoinMonitor.scala
integration/src/test/scala/co/topl/brambl/monitoring/BitcoinMonitorTest.scala
service-kit/project/build.properties

To capture affected blocks when a bitcoin reorg occurs.
If a reorg is detected (incoming block's parent does not match the last reported block), we find the common ancestor of the two. From this common ancestor, we unapply the chain (emit UnapplyBitcoinBlocks) leading to the previous last reported block. We also apply the new chain (emit AppliedBitcoinBlocks) leading to the newly adopted block.
Added an integration test
* Closes TSDK-801

TSDK-801 Support Bitcoin Reorgs to the Bitcoin Monitor

---

.gitignore
CHANGELOG.md
brambl-sdk/src/main/scala/co/topl/brambl/monitoring/BifrostMonitor.scala
integration/src/test/scala/co/topl/brambl/monitoring/BifrostMonitorTest.scala

Add a height field in the Bifrost monitor stream
We already queried bifrost for the Transactions. We utilized this call to retrieve the height from the header as well
- Verified accuracy of returned heights in the existing tests
- These tests found a bug (now fixed) that there was a gap in between reporting retroactive blocks and live blocks. The reason is because `.blockByDepth(1)` did not return the tip of the chain. This was replaced with `blockByDepth(0)`.
* closes TSDK-811

TSDK-811 Added Height Field to Bifrost Monitor

---

.github/workflows/_sbt_build.yml
.gitignore
CHANGELOG.md
brambl-sdk/src/main/scala/co/topl/brambl/dataApi/BifrostQueryAlgebra.scala
brambl-sdk/src/main/scala/co/topl/brambl/dataApi/BifrostQueryInterpreter.scala
brambl-sdk/src/main/scala/co/topl/brambl/monitoring/BifrostMonitor.scala
brambl-sdk/src/main/scala/co/topl/brambl/monitoring/BitcoinMonitor.scala
integration/src/test/scala/co/topl/brambl/monitoring/BifrostMonitorTest.scala
integration/src/test/scala/co/topl/brambl/monitoring/BitcoinMonitorTest.scala
integration/src/test/scala/co/topl/brambl/monitoring/package.scala
project/Dependencies.scala
project/metals.sbt
setupBifrostRegtest.sh

- Added integration test for the Bifrost Monitor to ensure reorgs are handled as expected
- Added the bifrost RPC function "makeBlock" to the BifrostQuery API. This is to force block production and is only meant to be used in "RegTest" mode.
- Bifrost and Bitcoin monitor APIs now return a resource containing their respective block stream.
- Retroactive reporting of existing blocks in the bifrost monitor is now inclusive (includes the starting block).
- Bifrost monitor's update stream is now self-contained. It's channel will now shutdown when the monitor is released. 
- The ZMQ subscriber that is used in the Bitcoin Monitor now stops when the monitor is released. Users no longer have to explicitly call ".stop()"
- Updated existing BitcoinMonitor and BifrostMonitor tests (including the …

TSDK-852 Changes to BifrostMonitor and BitcoinMonitor

---

brambl-sdk/src/main/scala/co/topl/brambl/monitoring/BitcoinMonitor.scala
integration/src/test/scala/co/topl/brambl/monitoring/BitcoinMonitorTest.scala
integration/src/test/scala/co/topl/brambl/monitoring/package.scala
project/Dependencies.scala

To resolve conflicting dependencies with bitcoin-s
- upgrade bitcoin-s to 1.9.9 and added 2 imports to BitcoinMonitor (Edmundo)
- Fixed failing tests due to this change (Diadem)
- Updated arguments to all calls to `getNewAddress` since the update changed the function signature
- Changed the way we connect 2 bitcoin nodes (using docker exec) since `addNode` was no longer working
Ensured all tests work again
* n/a

Update Bitcoin-s dependency

---

crypto/src/main/scala/co/topl/crypto/signing/eddsa/EC.scala

This PR updates a domain separation variable to more fully comply with the Ed25519 specification. The variable is question is used only in special circumstances and IS NOT currently being invoked, so there is no cause for concern.
Within the Ed25519 signing routine, this string used to prevent message collisions in order to constrain signatures produced by the routine. This string is described in the specification [here](https://datatracker.ietf.org/doc/html/rfc8032#section-8.6) and within the implementation is supposed to be represented by the UTF-8 encoding of the string, as illustrated in the bouncycastle implementation [here](https://github.com/bcgit/bc-java/blob/b8e4716f170a63986f8d3144445e3abff0e40475/core/src/main/java/org/bouncycastle/math/ec/rfc8032/Ed25519.java#L57). Also more …

MINOR - specify domain separation string encoding

---

build.sbt

The maven-release job keeps failing due to Too many Server Redirects (20). We are testing out a possible fix done by normalizing the artifact names (removing "+" from the version).
Applied the fix done in https://github.com/Topl/topl-btc-bridge/commit/ceb35cfb3b0c4c0063c57e5511d06ac152436cf1
Testing is done manually by seeing if the maven-release job is successful 
n/a

Fix maven deploy

---

.github/workflows/pr.yml
CHANGELOG.md
brambl-sdk/src/main/scala/co/topl/brambl/builders/MergingOps.scala
brambl-sdk/src/main/scala/co/topl/brambl/builders/TransactionBuilderApi.scala
brambl-sdk/src/main/scala/co/topl/brambl/builders/UserInputValidations.scala
brambl-sdk/src/main/scala/co/topl/brambl/syntax/TokenTypeIdentifierSyntax.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/MergingOpsSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/MergingSpecBase.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterAssetMergingSpec.scala
brambl-sdk/src/test/scala/co/topl/brambl/builders/TransactionBuilderInterpreterSpecBase.scala

To add support for TAMv2 asset merging.
- Added asset merging to the Transaction Builder API. This takes in UTXOs to merge, runs validations, and returns the resulting transaction
- Added MergingOps to contain merge logic; it contains the merging validators (describing what constitutes a compatible and valid merge) as well as the actual merge logic
- Added other user argument validation
- Added tests and helpers
Added unit tests and ensured all pass
* closes TSDK-580

TSDK-580 Implement Asset Merging
